name: Test

on:
  pull_request:
    paths:
      - 'action.yml'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Self Action Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Runs dockle action
        uses: ./
        with:
          image: hello-world

      - name: Runs dockle action with optional inputs
        uses: ./
        with:
          image: hello-world
          exit-code: '1'
          exit-level: 'FATAL'
